// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221023162743_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.PontosTuristicos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PontosTuristicos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60bf0db9-0f3b-4b58-a61c-d4beb1f07a96"),
                            Cidade = "Rio de Janeiro",
                            DataHoraCadastro = new DateTime(2022, 10, 23, 13, 27, 42, 739, DateTimeKind.Local).AddTicks(2330),
                            Descricao = "Principal ponto turístico do Rio de Janeiro",
                            Estado = "RJ",
                            Nome = "Cristo Redentor",
                            Referencia = ""
                        },
                        new
                        {
                            Id = new Guid("72c4c3f8-fc6e-4a07-9d8e-da169507ec5a"),
                            Cidade = "Rio de Janeiro",
                            DataHoraCadastro = new DateTime(2022, 10, 23, 13, 27, 42, 739, DateTimeKind.Local).AddTicks(2351),
                            Descricao = "Principal ponto turístico do Rio de Janeiro",
                            Estado = "RJ",
                            Nome = "Pão de Açúcar",
                            Referencia = ""
                        },
                        new
                        {
                            Id = new Guid("adc2579f-edd1-4fcc-ac66-f7caa8c4a52a"),
                            Cidade = "Foz do Iguaçu",
                            DataHoraCadastro = new DateTime(2022, 10, 23, 13, 27, 42, 739, DateTimeKind.Local).AddTicks(2355),
                            Descricao = "Patrimonio Natural da Humanidade.",
                            Estado = "PR",
                            Nome = "Cataratas do Iguaçu",
                            Referencia = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
