// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.PontosTuristicos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PontosTuristicos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e7bc293-3c0e-42f1-a6b8-4dd8718e800a"),
                            Cidade = "Rio de Janeiro",
                            Descricao = "Principal ponto turístico do Rio de Janeiro",
                            Estado = "RJ",
                            Nome = "Cristo Redentor",
                            Referencia = ""
                        },
                        new
                        {
                            Id = new Guid("5fd0a06f-da00-4c68-a80c-8c580e51f597"),
                            Cidade = "Rio de Janeiro",
                            Descricao = "Principal ponto turístico do Rio de Janeiro",
                            Estado = "RJ",
                            Nome = "Pão de Açúcar",
                            Referencia = ""
                        },
                        new
                        {
                            Id = new Guid("46d868de-15c4-4dbf-a506-9c8b76e7425f"),
                            Cidade = "Foz do Iguaçu",
                            Descricao = "Patrimonio Natural da Humanidade.",
                            Estado = "PR",
                            Nome = "Cataratas do Iguaçu",
                            Referencia = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
